# -*- coding: utf-8 -*-
"""alzheimers_test_set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NENOjZ47_Rg4OQKkiAfH-4azqfoSPyeh
"""

test_set = [
    {
        "question": "What are the early symptoms of Alzheimer's disease?",
        "expected_answer": "Early symptoms often include difficulties with word-finding, spatial awareness issues, and impaired reasoning or judgment. These symptoms may appear before noticeable memory loss."
    },
    {
        "question": "Can Alzheimer's be reversed?",
        "expected_answer": "Currently, Alzheimer’s cannot be reversed. However, early treatment can help manage symptoms and slow progression in some individuals."
    },
    {
        "question": "How does Alzheimer's affect memory?",
        "expected_answer": "Alzheimer’s progressively damages memory by first affecting short-term recall and gradually impairing long-term memory as the disease advances. This impacts daily activities and independence."
    },
    {
        "question": "What are biomarkers in Alzheimer's diagnosis?",
        "expected_answer": "Biomarkers are biological indicators like amyloid-beta or tau levels found in brain scans, cerebrospinal fluid, or blood. They help confirm Alzheimer’s and differentiate it from other conditions."
    },
    {
        "question": "Which stage is most commonly diagnosed in Alzheimer's?",
        "expected_answer": "Most individuals are diagnosed during the mild to moderate stages when symptoms become more noticeable. These include memory lapses and functional impairments in daily life."
    },
    {
        "question": "What are the behavioral changes in Alzheimer's?",
        "expected_answer": "Behavioral changes in Alzheimer's may include irritability, aggression, anxiety, and mood swings. These symptoms often become more pronounced as the disease progresses."
    },
    {
        "question": "How is Alzheimer’s diagnosed?",
        "expected_answer": "Alzheimer’s is diagnosed using cognitive assessments, clinical history, and imaging tools such as MRI and PET scans. Biomarker testing may also be used for confirmation."
    },
    {
        "question": "What are some treatable conditions that mimic Alzheimer’s?",
        "expected_answer": "Sleep disorders, medication side effects, infections, vitamin deficiencies, and depression can mimic Alzheimer’s. These conditions should be ruled out first as they may be reversible."
    },
    {
        "question": "How does Alzheimer's impact language?",
        "expected_answer": "People with Alzheimer’s may struggle to find the right words, follow conversations, or understand spoken and written language. These issues worsen as the disease progresses."
    },
    {
        "question": "What are the causes of Alzheimer’s?",
        "expected_answer": "Alzheimer’s is caused by a combination of genetic, environmental, and lifestyle factors. The accumulation of amyloid plaques and tau tangles in the brain is a hallmark of the disease."
    },
    {
        "question": "Is Alzheimer's hereditary?",
        "expected_answer": "Yes, Alzheimer’s can run in families, particularly early-onset cases. However, most cases are sporadic, and having a genetic risk doesn’t guarantee developing the disease."
    },
    {
        "question": "How does Alzheimer's differ from dementia?",
        "expected_answer": "Alzheimer’s is the most common form of dementia, but not all dementia is Alzheimer’s. Other types include vascular dementia and Lewy body dementia, which have distinct features."
    },
    {
        "question": "Can Alzheimer’s affect vision?",
        "expected_answer": "Yes, Alzheimer’s can cause visual-spatial difficulties, such as trouble judging distances or recognizing objects. These are not due to eye problems but brain processing issues."
    },
    {
        "question": "What stage of Alzheimer's involves personality changes?",
        "expected_answer": "Personality changes such as increased suspicion or withdrawal often occur in the moderate stage of Alzheimer’s. These changes may result from frustration or confusion."
    },
    {
        "question": "What is the role of caregivers in Alzheimer’s management?",
        "expected_answer": "Caregivers provide essential support by assisting with daily tasks, ensuring medication adherence, and managing behavioral symptoms. They also offer emotional support to patients."
    },
    {
        "question": "How does Alzheimer’s affect reasoning and judgment?",
        "expected_answer": "Alzheimer’s leads to poor decision-making, difficulty with problem-solving, and impaired ability to plan. This can affect financial management and safety awareness."
    },
    {
        "question": "What medications are used to treat Alzheimer’s?",
        "expected_answer": "Common medications include donepezil, rivastigmine, and memantine. These drugs help manage symptoms but do not stop or reverse disease progression."
    },
    {
        "question": "What lifestyle changes can help manage Alzheimer’s?",
        "expected_answer": "Engaging in physical activity, eating a brain-healthy diet, and maintaining cognitive engagement may help slow Alzheimer’s progression. Social interactions also provide benefits."
    },
    {
        "question": "Can early diagnosis help with Alzheimer’s treatment?",
        "expected_answer": "Yes, early diagnosis allows for timely treatment, better care planning, and access to support services. It may also help patients participate in clinical trials."
    },
    {
        "question": "What is mild cognitive impairment (MCI)?",
        "expected_answer": "MCI is a condition where individuals experience noticeable cognitive decline without significant interference in daily life. It can be a precursor to Alzheimer’s but not always."
    }
]